import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6E6E6',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0066FF',
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 30,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    zIndex: 3,
  },
  backIcon: {
    width: 20,
    height: 20,
    tintColor: '#FFF',
    marginRight: 10,
  },
  headerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'center',
    marginRight: 30,
  },
  boxInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    left: 0,
    right: 0,
    marginHorizontal: 0,
    paddingHorizontal: 20,
    padding: 20,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    position: 'absolute',
    top: 90,
    zIndex: 2,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  perfil: {
    width: 40,
    height: 40,
    marginRight: 12,
    resizeMode: 'contain',
  },
  nomeUnidade: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
  tipoConsulta: {
    fontSize: 13,
    color: '#666',
  },
  subtitulo: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 100,
    marginBottom: 40,
    color: '#333',
  },
  filtros: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
filtroBtn: {
  backgroundColor: '#0066FF',
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 20,
  alignItems: 'center',
  flexDirection: 'row',
  minWidth: 80,
  overflow: 'hidden',
},
filtroBtnSelecionado: {
    borderWidth: 2,
    borderColor: '#FFF',
  },
  filtroBtnTodos: {
  justifyContent: 'center',
  flexDirection: 'column',
  alignItems: 'center',
},

  filtroIcon: {
    width: 16,
    height: 16,
    marginRight: 6,
    resizeMode: 'contain',
    tintColor: '#FFF',
  },

  filtroText: {
    fontSize: 13,
    color: '#FFF',
    fontWeight: 'bold',
  },
  listaDatas: {
    paddingHorizontal: 20,
  },
  dataCard: {
    backgroundColor: '#FFF',
    height: 100,
    width: 140,
    padding: 14,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    elevation: 3,
  },
  semana: {
    fontSize: 13,
    color: '#444',
    marginBottom: 4,
  },
  dia: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
});

export default styles;
