import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6E6E6',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0066FF',
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 30,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    zIndex: 3,
  },
  backIcon: {
    width: 20,
    height: 20,
    tintColor: '#FFF',
    marginRight: 10,
  },
  headerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'center',
    marginRight: 30,
  },
  boxInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    width: '90%',
    alignSelf: 'center',
    padding: 20,
    borderRadius: 16,
    position: 'absolute',
    top: 95,
    zIndex: 2,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  perfil: {
    width: 40,
    height: 40,
    marginRight: 12,
    resizeMode: 'contain',
  },
  nomeUnidade: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
  tipoConsulta: {
    fontSize: 13,
    color: '#666',
  },
  subtitulo: {
    textAlign: 'center',
    fontSize: 14,
    marginTop: 140, 
    marginBottom: 15,
    fontWeight: 'bold',
    color: '#333',
  },
  filtros: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  filtroBtn: {
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    alignItems: 'center',
    elevation: 2,
    flexDirection: 'row',
    gap: 4,
  },
  filtroIcon: {
    width: 16,
    height: 16,
    marginRight: 6,
    resizeMode: 'contain',
  },
  filtroText: {
    fontSize: 13,
    color: '#0066FF',
    fontWeight: 'bold',
  },
  listaDatas: {
    paddingHorizontal: 20,
  },
  dataCard: {
    backgroundColor: '#FFF',
    height: 100,
    width: 140,
    padding: 14,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    elevation: 3,
  },
  semana: {
    fontSize: 13,
    color: '#444',
    marginBottom: 4,
  },
  dia: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
});

export default styles;
